### ISSUE TITLE
Failing to process dates in v 2.0.5.1_beta_2020-01-18

### ISSUE THREAD

**Issue by IanBezanson** [HandyGuySoftware/dupReport#141] opened 2020-03-23 13:12 UTC
Hi,

I'm seeing issues when processing the newest version of Duplicati around the date/time formats (e.g. _3/22/2020 1:02:32 PM_). 

From the duplicati system-info, here's what I see:
**Date/time strings: dddd, MMMM d, yyyy - h:mm:ss tt**

in the rc file, trying _dateformat = MM/DD/YYYY_

any thoughts?

**Comment by HandyGuySoftware** [comment] 2020-03-23 13:40
What specific error messages are you seeing in dupReport? If you can run the program with -v3 option please attach the bottom portion of the log file so I can try to figure out what's happening.

**Comment by IanBezanson** [comment] 2020-03-23 14:55
[logsnippet.txt](https://github.com/HandyGuySoftware/dupReport/files/4370139/logsnippet.txt)

Attached!

**Comment by HandyGuySoftware** [comment] 2020-03-24 00:58
I couldn't see anything obvious in the snippet you sent, however there are a lot of unusual characters in the email extract:

DeletedFiles: 24 **=0D=0A** DeletedFolders: 0 **=0D=0A** ModifiedFiles:

It seems as if your email program is adding these extra characters somewhere along the way. Has the program worked previously and just started malfunctioning, or has it not worked all along? Also, do all the emails in the log file look like this? Check all the "***** Next Message:" sections to compare them.

Finally, how are you running dupReport?
- O.S. & version
- Email service
- POP3 or IMAP?

I don't have any immediate answers, but hopefully we can dig enough to find out.

**Comment by IanBezanson** [comment] 2020-03-25 11:24
It had been running okay, but I was starting to run into issues with Duplicati 2.0.3.3 on some of our Debian linux servers. I upgraded to 2.0.5.1 on a handful of servers with Debian 10.x release (and a newer version of mono) and now that application runs happily (producing backups on the end host).

The dupReport service ran fine with email notifications from older versions, but seems cranky with the produced date format of the newest Duplicati.

dupReport itself is running on Debian 9.12.
Email service is Google Mail
IMAP

**Comment by HandyGuySoftware** [comment] 2020-03-28 13:35
I've been trying to research what the problem might be but am coming up short. Is dupReport still giving you problems?

**Comment by IanBezanson** [comment] 2020-03-28 16:08
I am, but will try a fresh pull of the code and new config. Will do that and report back.

**Comment by IanBezanson** [comment] 2020-04-08 11:54
Hi, sorry for the delay. Just pulled a fresh copy this morning, configured it, and tried again.

Running into similar issues. All servers we're monitoring are running the same version of Duplicati (Version: 2.0.5.1 (2.0.5.1_beta_2020-01-18), with different date formats reporting back to email (landing in Google mail). One example seems to be (from email report):
```
EndTime: 4/7/2020 1:00:10 AM (1586232010)
BeginTime: 4/7/2020 1:00:00 AM (1586232000)
```

where dupReport isn't able to parse from settings :
```
dateformat = MM/DD/YYYY
timeformat = HH:MM:SS
```

the log seems to actually be choking on the timeformat, but my guess is the lack of preceding zeros in the dateformat is affecting it:

> dremail.parenOrRaw(4/5/2020 1:00:12 PM (1586102412)=0D=0ABeginTime: 4/5/202=, MM/DD/YYYY, HH:MM:SS, -14400)
> retval=[1586102412]
> dremail.parenOrRaw(4/5/202=, MM/DD/YYYY, HH:MM:SS, -14400)
> drDateTime.toTimestamp(4/5/202=, MM/DD/YYYY, HH:MM:SS, -14400)
> Can't find a match for time pattern HH:MM:SS in date/time string 4/5/202=.
> This is likely caused by an email using a different date or time format than expected,
> particularly if you're collecting emails from multiple locations or time zones.
> Please check the 'dateformat=' and 'timeformat=' value(s) in the [main] section
> and any [<source>-<destination>] sections of your .rc file for accuracy.

**Comment by HandyGuySoftware** [comment] 2020-04-08 17:16
The problem isn't with the date format, dR should handle leading or non-leading 0's in a date/time form. I believe the actual problem is the use of Content Transfer Encoding on the message. That's the  **=0D=0A** text you see in the emails. This has cropped up before with some emails, but I've never been able to pin down the exact problem.

I've uploaded some code to the [Issue_141 branch on GitHub](https://github.com/HandyGuySoftware/dupReport/tree/Issue_141). That code does some checking for CTE and attempts to adjust the payload appropriately. I'm not sure it will fix the problem (yet), and it may even crash if I didn't code it properly, but the resulting log file should give enough clues to see if I'm on the right path.

Make sure you run it with the verbose option set (-v3).

**Comment by IanBezanson** [comment] 2020-04-08 18:06
Thanks! The attempt failed rather miserably with errors. The log is attached.

[dupReport.log](https://github.com/HandyGuySoftware/dupReport/files/4452049/dupReport.log)

**Comment by HandyGuySoftware** [comment] 2020-04-08 19:22
Believe it or not, this was actually a huge success!

```
 Started:=0D=0A duplicati-b71062c8cd83d4f899ae8dc0549d4631c.dbloc=
k.zip.aes (49.91 MB),=0D=0A    2020-04-05 10:05:03 -03 -=0D=0A [I=
nformation-Duplicati.Library.Main.BasicResults-BackendEvent]: Bac=
kend event: Put - Started:=0D=0A duplicati-b75e27cfda0b04d4c9a2de=
487f8df6f45.dblock.zip.aes (49.92 MB),=0D=0A    2020-04-05 10:05:=
05 -03 -=0D=0A [Information-Duplicati.Library.Main.BasicResults-B=
ackendEvent]: Backend event: Put - Completed:=0D=0A duplicati-b87=
c20f3c2f0d47ff8f37975149110875.dblock.zip.aes (49.96 MB),=0D=0A  =
  2020-04-05 10:05:05 -03 -=0D=0A [Information-Duplicati.Library.=
Main.BasicResults-BackendEvent]: Backend event: Put - Started:=0D=0A=
 duplicati-i57ce8524c3884f9f9796412b239547a4.dindex.zip.aes (40.9=
8 KB),=0D=0A    2020-04-05 10:05:06 -03 -=0D=0A [Information-Dupl=
icati.Library.Main.BasicResults-BackendEvent]: Backend event: Put=
 - Completed:=0D=0A duplicati-i57ce8524c3884f9f9796412b239547a4.d=
index.zip.aes (40.98 KB),=0D=0A...=0D=0A]=0D=0ALimitedWarnings: [=
]=0D=0ALimitedErrors: []=0D=0A

]
New (quopri) Message Body=[b'DeletedFiles: 66\r\nDeletedFolders: 0\r\nModifiedFiles: 16\r\nExaminedFiles: 616888\r\nOpenedFiles: 2976\r\nAddedFiles: 2960\r\nSizeOfModifiedFiles: 2169329676\r\nSizeOfAddedFiles: 1375440903\r\nSizeOfExaminedFiles: 241680554932\r\nSizeOfOpenedFiles: 3544782867\r\nNotProcessedFiles: 0\r\nAddedFolders: 5\r\nTooLargeFiles: 0\r\nFilesWithError: 0\r\nModifiedFolders: 0\r\nModifiedSymlinks: 0\r\nAddedSymlinks: 0\r\nDeletedSymlinks: 0\r\nPartialBackup: False\r\nDryrun: False\r\nMainOperation: Backup\r\nParsedResult: Success\r\nVersion: 2.0.5.1 (2.0.5.1_beta_2020-01-18)\r\nEndTime: 05/04/2020 10:14:17 (1586092457)\r\nBeginTime: 05/04/2020 10:00:00 (1586091600)\r\nDuration: 00:14:17.2211230\r\nMessagesActualLength: 405\r\nWarningsActualLength: 0\r\nErrorsActualLength: 0\r\nLimitedMessages: [\r\n    2020-04-05 10:00:00 -03 -\r\n [Information-Duplicati.Library.Main.Controller-StartingOperation]: The operation Backup has started,\r\n    2020-04-05 10:01:04 -03 -\r\n [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Started:  (),\r\n    2020-04-05 10:04:32 -03 -\r\n [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: List - Completed:  (19.54 KB),\r\n    2020-04-05 10:05:02 -03 -\r\n [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started:\r\n duplicati-b87c20f3c2f0d47ff8f37975149110875.dblock.zip.aes (49.96 MB),\r\n    2020-04-05 10:05:02 -03 -\r\n [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started:\r\n duplicati-be7ae5873ae5e47bd93a38bbce97f8e21.dblock.zip.aes (49.92 MB),\r\n    2020-04-05 10:05:02 -03 -\r\n [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started:\r\n duplicati-b71062c8cd83d4f899ae8dc0549d4631c.dblock.zip.aes (49.91 MB),\r\n    2020-04-05 10:05:03 -03 -\r\n [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started:\r\n duplicati-b75e27cfda0b04d4c9a2de487f8df6f45.dblock.zip.aes (49.92 MB),\r\n    2020-04-05 10:05:05 -03 -\r\n [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed:\r\n duplicati-b87c20f3c2f0d47ff8f37975149110875.dblock.zip.aes (49.96 MB),\r\n    2020-04-05 10:05:05 -03 -\r\n [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Started:\r\n duplicati-i57ce8524c3884f9f9796412b239547a4.dindex.zip.aes (40.98 KB),\r\n    2020-04-05 10:05:06 -03 -\r\n [Information-Duplicati.Library.Main.BasicResults-BackendEvent]: Backend event: Put - Completed:\r\n duplicati-i57ce8524c3884f9f9796412b239547a4.dindex.zip.aes (40.98 KB),\r\n...\r\n]\r\nLimitedWarnings: []\r\nLimitedErrors: []\r\n\r\n\r\n']
EmailServer.searchMesagePart(msgField, DeletedFiles: \d+, 0, 0
```

The first part shows the CTE encoding and the second part shows the decoded email body. That's *exactly* what I was looking for. Now, the fact that it crashed horribly is just a side effect of not following through on the aftermath of decoding the body. dupReport expects each status line in the body to be on its own line. However, the CTE decoding process strips the newlines out and presents the whole body as a single line. That's why it crashed.

I am wondering what the output would be if you instructed Duplicati to send JSON output instead of text (job->Edit->Options->Advanced options->send-mail-result-output-format = JSON)? If you could do that and send the resulting log file along, that would be great.

This may take a bit to correct, but I'm pretty sure I know what's happening now. Stay tuned...

**Comment by IanBezanson** [comment] 2020-04-08 19:51
Awesome, and sure will do that with a few of them and we'll see how it goes.

**Comment by IanBezanson** [comment] 2020-04-08 19:57
I've changed up 10 of the servers to report in JSON. I can clear out the other server mail before testing again once you've made changes. Happy to go on the adventure with you!

**Comment by HandyGuySoftware** [comment] 2020-04-08 21:31
I just upload some new code to the Issue_141 branch. Let me know if it crashes more gently.

**Comment by IanBezanson** [comment] 2020-04-08 23:22
Perfect, thanks I've grabbed it and will run again tomorrow.

**Comment by IanBezanson** [comment] 2020-04-09 11:22
I re-ran this morning against the JSON output and attached the results. I did realize that a handful of older machines are running a slightly older version of Duplicati (they don't support newer Mono version), so they don't support the JSON format flag. Hopefully we'll be able to mix and match formats once this gets sorted?

[dupReport.log](https://github.com/HandyGuySoftware/dupReport/files/4455820/dupReport.log)

**Comment by HandyGuySoftware** [comment] 2020-04-09 12:15
Ugh. That one didn't go so well, crashed out too early and in an unexpected place. Just uploaded new code. Let's try the following:

1. Run a backup with normal ("Duplicati") output. If (when) it crashes copy the error message you get.
1. Run dupReport, save the log file
1. Run a backup with JSON output. If (when) it crashes copy the error message you get.
1. Run dupReport, save the log file

Upload both logs and the error messages and let's see what that shows.

**Comment by IanBezanson** [comment] 2020-04-10 12:59
Seems to work on the newest version from the latest Duplicati release with both JSON and regular format now (although we're also into double-digit days for the month.  I'm going to run a few more tests and then isolate for older versions of Duplicati.

**Comment by IanBezanson** [comment] 2020-04-10 14:05
It seems happy now. So maybe it's fixed or maybe it because we've hit double-digit days? I have it running on regular HTML from both old and new duplicati setups and dupReport is running happily

**Comment by HandyGuySoftware** [comment] 2020-04-10 14:30
That's great to hear! I'm happy to keep this open until the beginning of next month to make sure that single-digit days don't cause another problem. Let me know how your testing goes. 

Thanks for helping me chase this down. As I said, this has come up a couple of times and I've had a terrible time trying to fix it. Thanks for the assistance. :-)

**Comment by IanBezanson** [comment] 2020-04-10 16:52
Sounds great and thank you for all of the help.

**Comment by HandyGuySoftware** [comment] 2020-04-24 18:11
Added to version 3.0.0 code.

**Comment by HandyGuySoftware** [comment] 2020-05-07 15:06
Hi @IanBezanson , 

Just checking in to see if this fix is still working after the month rollover?

HG

**Comment by IanBezanson** [comment] 2020-05-07 16:57
Thanks for checking - things seem happy!

**Comment by HandyGuySoftware** [comment] 2020-05-07 18:52
OK, I'll close this out and update the master branch with the new code. Thanks for the help tracking this down!

**Closed as completed by HandyGuySoftware** 2020-05-07 18:52 UTC
Labels: bug, 2.2.11
