### ISSUE TITLE
DB not updating

### ISSUE THREAD

**Issue by TowerBR** [HandyGuySoftware/dupReport#18] opened 2017-11-02 14:26 UTC
dubReport is running properly, and I'm getting the emails with the reports, but they're empty.

The log file is being updated, but the DB is not.

![report](https://user-images.githubusercontent.com/33122168/32331046-015a104a-bfc9-11e7-86b7-444adb8035ff.jpg)

**Comment by HandyGuySoftware** [comment] 2017-11-02 14:55
Hmm, that's not good. It looks like dR is rejecting all the emails as not messages of interest. If it were recognizing any of them there should be at least one source/destination pair listed in the report. Not sure why that is, though.

Please try the following:

1. First, make sure you are running the latest version (2.0.3). Use dupReport.py -V to find out. If not, you can get 2.0.3 from the beta branch of the project.
2. Clear out the database by running dupReport.py -i
3. Run the program with full logging, dupReport.py -v3

Once that is complete, if the problem hasn't corrected itself please post the resulting dupReport.log file so I can see what's happening. We should be able to figure it out quickly.

**Comment by TowerBR** [comment] 2017-11-03 01:19
Nope, it's finding "interesting" messages, see some:

Message ID [<0MDTSPRGR2U4.Q9WYD09692IM@Note4>] does not exist. Adding to DB
Subject=[Duplicati Backup report for teste].
Message ID [<SY2RSPSGR2U4.X14Z2YWECVFI@Note4>] does not exist. Adding to DB
Subject=[Duplicati Backup report for teste].
Message ID [<ABMYFPTGR2U4.108HVGKXTLPP1@Note4>] does not exist. Adding to DB
Subject=[Duplicati Backup report for teste].

But the BP isn't being updated.

I'm running 2.0.2 (not beta), I'll try 2.0.3.

**Comment by HandyGuySoftware** [comment] 2017-11-03 02:02
Ah, I see the issue. Your backup name has to be in "source-destination" format for dupReport to work. Check out the README file under "Source-Destination Pairs" for an explanation. If you rename your backup to the proper format the report should run fine. This is the same in 2.0.2 or 2.0.3.

Let me know if that works for you.

**Comment by HandyGuySoftware** [comment] 2017-11-03 15:44
Closed as a configuration error.

**Comment by TowerBR** [comment] 2017-11-04 01:56
"teste" was just my first backup job and it really was not named in the correct form, but the rest are:
![jobs](https://user-images.githubusercontent.com/33122168/32401221-00a000fe-c0f2-11e7-8570-194b0cc8a157.jpg)

I'm now using version 2.0.3, the log is being populated correctly, the DB is also being populated:

![dbemails](https://user-images.githubusercontent.com/33122168/32401331-54cb158c-c0f3-11e7-930d-3f8b0bb162bc.jpg)
![dbbackupsets](https://user-images.githubusercontent.com/33122168/32401337-6103d44c-c0f3-11e7-92cb-b383e028813c.jpg)



But the emails are not being sent, and I am getting this error message:

Traceback (most recent call last):
  File "C:\_Arquivos\dupReport\dupReport.py", line 868, in <module>
    create_summary_report()
  File "C:\_Arquivos\dupReport\dupReport.py", line 646, in create_summary_report
    d0 = datetime.date(int(then[0]),int(then[1]), int(then[2]))
ValueError: invalid literal for int() with base 10: '2000-01-01'

**Comment by HandyGuySoftware** [comment] 2017-11-04 02:22
Hmmm. Please post the last 50 lines from the log file and I'll see what I can figure out from there.

**Comment by TowerBR** [comment] 2017-11-04 02:32
I deleted the DB and generated a new one, to get rid of those '2000-01-01', but it didn't work:

![db2](https://user-images.githubusercontent.com/33122168/32401520-21d620aa-c0f7-11e7-8538-419628d28819.jpg)

And now I'm getting this error:



```
Traceback (most recent call last):
  File "C:\_Arquivos\dupReport\dupReport.py", line 940, in <module>
    process_mailbox_imap(mailBox)
  File "C:\_Arquivos\dupReport\dupReport.py", line 795, in process_mailbox_imap
    mParts = process_message(msg)                # Process message into parts
  File "C:\_Arquivos\dupReport\dupReport.py", line 541, in process_message
    dateParts['endSaveDate'] = convert_date_time(statusParts['endTimeStr'])[0]
  File "C:\_Arquivos\dupReport\dupReport.py", line 376, in convert_date_time
    elif ((timePart[0] != "12") and (dtSplit[2] == 'PM')):
IndexError: list index out of range
```



Here is the end of the log:

```
DeletedFiles:` 0
DeletedFolders: 0
ModifiedFiles: 0
ExaminedFiles: 4437
OpenedFiles: 4253
AddedFiles: 4252
SizeOfModifiedFiles: 0
SizeOfAddedFiles: 12180491196
SizeOfExaminedFiles: 12609068584
SizeOfOpenedFiles: 12180491196
NotProcessedFiles: 0
AddedFolders: 1058
TooLargeFiles: 0
FilesWithError: 0
ModifiedFolders: 0
ModifiedSymlinks: 0
AddedSymlinks: 0
DeletedSymlinks: 0
PartialBackup: False
Dryrun: False
MainOperation: Backup
ParsedResult: Warning
VerboseOutput: True
VerboseErrors: False
EndTime: 02/11/2017 17:31:20
BeginTime: 02/11/2017 14:28:35
Duration: 03:02:45.1297131
Messages: [
    removing file listed as Temporary: duplicati-20171101T144721Z.dlist.zip.aes,
    promoting uploaded complete file from Uploading to Uploaded: duplicati-ieebd840f6bc840d6a2f0c3e73c516788.dindex.zip.aes,
    promoting uploaded complete file from Uploading to Uploaded: duplicati-bc5da246202ed45b18d35b3532f74bf19.dblock.zip.aes,
    removing incomplete remote file listed as Uploading: duplicati-i4fc918e9a89248feaf543c71e3dd817f.dindex.zip.aes,
    scheduling missing file for deletion, currently listed as Uploading: duplicati-b4e32dd81a87b42d6af3434c83ecdbf5f.dblock.zip.aes,
    scheduling missing file for deletion, currently listed as Uploading: duplicati-i705192d93e2547f6928e401ba46347f1.dindex.zip.aes,
    scheduling missing file for deletion, currently listed as Uploading: duplicati-bf8491c21bb124a91a90800014dfce834.dblock.zip.aes,
    scheduling missing file for deletion, currently listed as Uploading: duplicati-i0e21f3d8364b49b091eb5853bfc743d5.dindex.zip.aes,
    Re-creating missing index file for duplicati-bc5da246202ed45b18d35b3532f74bf19.dblock.zip.aes,
    Renaming "duplicati-b97aa1104d4ad4a3186dc90523ef43ace.dblock.zip.aes" to "duplicati-b5c0c45a9d155417789cac13a5b00638c.dblock.zip.aes",
    Renaming "duplicati-bc71a9b525b3740e38f0035a4eab05f51.dblock.zip.aes" to "duplicati-b339d4e4707e945988075a679ac6e393a.dblock.zip.aes",
    Stopping backup operation on request
]
Warnings: [
    Expected there to be a temporary fileset for synthetic filelist (4, duplicati-b012525d488384253bc8c933489efd9b5.dblock.zip.aes), but none was found?
]
Errors: []

]
decode=[('<DL48IAUIR2U4.K36W90MVQ18V@Note4>', None)]
messageId=[<DL48IAUIR2U4.K36W90MVQ18V@Note4>]
db_search_message() for messageId=[<DL48IAUIR2U4.K36W90MVQ18V@Note4>]
SELECT messageId FROM emails WHERE messageId='<DL48IAUIR2U4.K36W90MVQ18V@Note4>'
Message ID [<DL48IAUIR2U4.K36W90MVQ18V@Note4>] does not exist. Adding to DB
Subject=[Duplicati Backup report for GEA-Dropbox]
emailDate=[2017-11-02]  emailTime=[15:31:34]
srcregex=[\w*\-]  destRegex=[\-\w*]
source=[GEA] dest=[Dropbox] Date=[2017-11-02]  Time=[15:31:34] Subject=[Duplicati Backup report for GEA-Dropbox]
db_search_srcdest_pair(GEA, Dropbox)
SELECT source, destination FROM backupsets WHERE source='GEA' AND destination='Dropbox'
Source/Destination pair [GEA/Dropbox] already in database.
Body=[DeletedFiles: 0

DeletedFolders: 0

ModifiedFiles: 0

ExaminedFiles: 4437

OpenedFiles: 4253

AddedFiles: 4252

SizeOfModifiedFiles: 0

SizeOfAddedFiles: 12180491196

SizeOfExaminedFiles: 12609068584

SizeOfOpenedFiles: 12180491196

NotProcessedFiles: 0

AddedFolders: 1058

TooLargeFiles: 0

FilesWithError: 0

ModifiedFolders: 0

ModifiedSymlinks: 0

AddedSymlinks: 0

DeletedSymlinks: 0

PartialBackup: False

Dryrun: False

MainOperation: Backup

ParsedResult: Warning

VerboseOutput: True

VerboseErrors: False

EndTime: 02/11/2017 17:31:20

BeginTime: 02/11/2017 14:28:35

Duration: 03:02:45.1297131

Messages: [

    removing file listed as Temporary: duplicati-20171101T144721Z.dlist.zip.aes,

    promoting uploaded complete file from Uploading to Uploaded: duplicati-ieebd840f6bc840d6a2f0c3e73c516788.dindex.zip.aes,

    promoting uploaded complete file from Uploading to Uploaded: duplicati-bc5da246202ed45b18d35b3532f74bf19.dblock.zip.aes,

    removing incomplete remote file listed as Uploading: duplicati-i4fc918e9a89248feaf543c71e3dd817f.dindex.zip.aes,

    scheduling missing file for deletion, currently listed as Uploading: duplicati-b4e32dd81a87b42d6af3434c83ecdbf5f.dblock.zip.aes,

    scheduling missing file for deletion, currently listed as Uploading: duplicati-i705192d93e2547f6928e401ba46347f1.dindex.zip.aes,

    scheduling missing file for deletion, currently listed as Uploading: duplicati-bf8491c21bb124a91a90800014dfce834.dblock.zip.aes,

    scheduling missing file for deletion, currently listed as Uploading: duplicati-i0e21f3d8364b49b091eb5853bfc743d5.dindex.zip.aes,

    Re-creating missing index file for duplicati-bc5da246202ed45b18d35b3532f74bf19.dblock.zip.aes,

    Renaming "duplicati-b97aa1104d4ad4a3186dc90523ef43ace.dblock.zip.aes" to "duplicati-b5c0c45a9d155417789cac13a5b00638c.dblock.zip.aes",

    Renaming "duplicati-bc71a9b525b3740e38f0035a4eab05f51.dblock.zip.aes" to "duplicati-b339d4e4707e945988075a679ac6e393a.dblock.zip.aes",

    Stopping backup operation on request

]

Warnings: [

    Expected there to be a temporary fileset for synthetic filelist (4, duplicati-b012525d488384253bc8c933489efd9b5.dblock.zip.aes), but none was found?

]

Errors: []



]
statusParts['failed']=[]
convert_date_time(02/11/2017 17:31:20)

]
```

**Comment by HandyGuySoftware** [comment] 2017-11-04 02:54
OK, I see what the issue is. I assumed that the dates & times from the report have "AM" or "PM" in them (since that's what I've always seen). Your format just uses 24-hour time (must be a locale setting somewhere), so no need for AM/PM. When the program tries to find them it is crashing. Now that I know what to look for I can code up a fix. Please have a bit of patience, but I should be able to code up a fix this weekend.

Thanks for the additional info.

**Comment by TowerBR** [comment] 2017-11-04 02:57
I'm glad to help! Thank you for your attention.

**Comment by HandyGuySoftware** [comment] 2017-11-04 15:22
TowerBR,

Please pull down the 2.0.3_Issue_18 branch and try that code. I made a small change to the date/time handling routine that should fix the problem. Let me know if that works for you.

**Comment by TowerBR** [comment] 2017-11-04 18:10
Worked perfectly! Thanks a lot!

(note: "GEA-Dropbox" is still running for the first time, that's the reason for the different message)

![report](https://user-images.githubusercontent.com/33122168/32408090-92ef2782-c179-11e7-8541-772f5ed7bc00.png)

![dbbackupsets](https://user-images.githubusercontent.com/33122168/32408092-a2a9c754-c179-11e7-8f1f-087eabd017ff.png)

![dbemails](https://user-images.githubusercontent.com/33122168/32408096-a980b510-c179-11e7-91f9-23c273c4887b.png)

Log:

```
******** dupReport Log - Start: Sat Nov  4 15:55:52 2017
Logfile=[C:\_Arquivos\dupReport/dupReport.log]  appendlog=[False]  logLevel=[1]
Using IMAP incoming transport. Server=imap.gmail.com Port=993 Encryption=tls
Processing IMAP mailbox...
process_mailbox_imap()
process_message()
db_search_message() for messageId=[<S7IAWFJGR2U4.QIPOZ15GQQOO2@Note4>]
Message ID [<S7IAWFJGR2U4.QIPOZ15GQQOO2@Note4>] does not exist. Adding to DB
Message [<S7IAWFJGR2U4.QIPOZ15GQQOO2@Note4>] is not a Message of Interest.
process_message()
db_search_message() for messageId=[<LQJLAJKGR2U4.34LI0HZ8WLAL3@Note4>]
Message ID [<LQJLAJKGR2U4.34LI0HZ8WLAL3@Note4>] does not exist. Adding to DB
Message [<LQJLAJKGR2U4.34LI0HZ8WLAL3@Note4>] is not a Message of Interest.
process_message()
db_search_message() for messageId=[<DL48IAUIR2U4.K36W90MVQ18V@Note4>]
Message ID [<DL48IAUIR2U4.K36W90MVQ18V@Note4>] does not exist. Adding to DB
db_search_srcdest_pair(GEA, Dropbox)
convert_date_time(02/11/2017 17:31:20)
convert_date_time(02/11/2017 17:31:20)
convert_date_time(02/11/2017 14:28:35)
convert_date_time(02/11/2017 14:28:35)
build_email_sql_statement(()
process_message()
db_search_message() for messageId=[<59fbc975.4164370a.d4755.1e9e@mx.google.com>]
Message ID [<59fbc975.4164370a.d4755.1e9e@mx.google.com>] does not exist. Adding to DB
Message [<59fbc975.4164370a.d4755.1e9e@mx.google.com>] is not a Message of Interest.
process_message()
db_search_message() for messageId=[<B9LAV1IXR2U4.TZ2ZIQ66XUP81@Note4>]
Message ID [<B9LAV1IXR2U4.TZ2ZIQ66XUP81@Note4>] does not exist. Adding to DB
db_search_srcdest_pair(local_folders_Arquivo_morto, Dropbox)
convert_date_time(04/11/2017 01:26:13)
convert_date_time(04/11/2017 01:26:13)
convert_date_time(03/11/2017 20:27:27)
convert_date_time(03/11/2017 20:27:27)
build_email_sql_statement(()
process_message()
db_search_message() for messageId=[<JGQFSCVXR2U4.AZ1S9J1I65MM1@Note4>]
Message ID [<JGQFSCVXR2U4.AZ1S9J1I65MM1@Note4>] does not exist. Adding to DB
db_search_srcdest_pair(TD, Dropbox)
convert_date_time(04/11/2017 02:14:31)
convert_date_time(04/11/2017 02:14:31)
convert_date_time(04/11/2017 02:13:24)
convert_date_time(04/11/2017 02:13:24)
build_email_sql_statement(()
create_summary_report()
create_email_text()
create_email_text()
create_email_text()
create_email_text()
create_email_text()
create_email_text()
create_email_text()
create_email_text()
create_email_text()
create_email_text()
Program completed in 24.161 seconds. Exiting
```

**Comment by TowerBR** [comment] 2017-11-04 18:10
I don't know if it could be a problem, but "lastDate" (backupsets table) is as "yyyy/dd/mm" and "emailDate"(emails table) is as "yyyy/mm/dd". But the dates in the report are correct!

**Closed as completed** 2017-11-04 19:09 UTC
Labels: bug, 2.0.3
