### ISSUE TITLE
sslv3 illegal parameter error

### ISSUE THREAD

**Issue by g1bs0nsg** [HandyGuySoftware/dupReport#129] opened 2020-02-09 16:51 UTC
I've been running dupReport for quite awhile and never had any issues, but lately I have started getting the following:

`Traceback (most recent call last):
  File "/opt/dupReport/dupReport.py", line 297, in <module>
    globs.outServer.sendEmail(msgHtml, msgText)
  File "/opt/dupReport/dremail.py", line 575, in sendEmail
    self.connect()
  File "/opt/dupReport/dremail.py", line 165, in connect
    self.server.starttls()
  File "/usr/lib64/python3.6/smtplib.py", line 771, in starttls
    server_hostname=self._host)
  File "/usr/lib64/python3.6/ssl.py", line 365, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 773, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1033, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 645, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_ILLEGAL_PARAMETER] sslv3 alert illegal parameter (_ssl.c:877)
`
The last line I get in dupReport.log is:

`Initial connect using SMTP`

I made sure to upgrade to the latest version, 2.2.10.  Running Python 3.6.8 on a CentOS 7 system. 

I'm sure something has probably changed on my host that has started this, it's smtp.1and1.com that I use for the outgoing emails. 

Occasionally if I just run it over and over one will eventually send out correctly, it's very odd.

**Comment by HandyGuySoftware** [comment] 2020-02-09 18:56
@g1bs0nsg,

I uploaded some test code to see if we can figure out what's going on. Download the [Issue_129 branch](https://github.com/HandyGuySoftware/dupReport/tree/Issue_129) and run the program with the -v3 option to see if you get the same error. 

If you do, look in the log file and see if the added debug statements give you any more info on what may be happening. If not, upload them here and I'll take a look. NOTE: the new debug code in the log file will include your SMPT ID and password, so make sure to mask those if you upload them here.

Hope this will help.

HG

**Comment by g1bs0nsg** [comment] 2020-02-09 21:52
I still get the error, I ran it 3 times in a row changing nothing in between, the first two failed and I get this log:

[dupReport.log](https://github.com/HandyGuySoftware/dupReport/files/4177928/dupReport.log)

The last one succeeded and I get this log:

[dupReportSuccess.log](https://github.com/HandyGuySoftware/dupReport/files/4177929/dupReportSuccess.log)

Seems as though for whatever reason it will randomly die off at the logging in to server step with the illegal parameter error, but other times works fine.

**Comment by HandyGuySoftware** [comment] 2020-02-09 22:34
OK, some more debugging code added to the Issue_129 branch. Give it a try and see what happens.

The fact that it runs sometimes leads me to believe it's a problem with the SMTP connect, not necessarily with the dupReport code. Hopefully the error message it gets this time might help narrow it down.

**Comment by g1bs0nsg** [comment] 2020-02-09 23:21
Hmmm... nothing new in the log this time, but I got another exception:

`Traceback (most recent call last):
  File "/opt/test/dupReport/dremail.py", line 169, in connect
    self.server.starttls()
  File "/usr/lib64/python3.6/smtplib.py", line 771, in starttls
    server_hostname=self._host)
  File "/usr/lib64/python3.6/ssl.py", line 365, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 773, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1033, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 645, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_ILLEGAL_PARAMETER] sslv3 alert illegal parameter (_ssl.c:877)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/test/dupReport/dupReport.py", line 297, in <module>
    globs.outServer.sendEmail(msgHtml, msgText)
  File "/opt/test/dupReport/dremail.py", line 589, in sendEmail
    self.connect()
  File "/opt/test/dupReport/dremail.py", line 170, in connect
    except Exception_tls:
NameError: name 'Exception_tls' is not defined
`

**Comment by g1bs0nsg** [comment] 2020-02-10 00:05
My python skills aren't great, but I changed the except line in dremail.py to simply:

```
try:
    self.server.starttls()
except Exception as e:
    print(e)
```

And commented out the rest. When I run that, I get the following traceback:

```
[SSL: SSLV3_ALERT_ILLEGAL_PARAMETER] sslv3 alert illegal parameter (_ssl.c:877)
Traceback (most recent call last):
  File "/usr/lib64/python3.6/smtplib.py", line 354, in send
    self.sock.sendall(s)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/test/dupReport/dupReport.py", line 297, in <module>
    globs.outServer.sendEmail(msgHtml, msgText)
  File "/opt/test/dupReport/dremail.py", line 591, in sendEmail
    self.connect()
  File "/opt/test/dupReport/dremail.py", line 182, in connect
    retVal, retMsg = self.server.login(self.accountname, self.passwd)
  File "/usr/lib64/python3.6/smtplib.py", line 721, in login
    initial_response_ok=initial_response_ok)
  File "/usr/lib64/python3.6/smtplib.py", line 631, in auth
    (code, resp) = self.docmd("AUTH", mechanism + " " + response)
  File "/usr/lib64/python3.6/smtplib.py", line 420, in docmd
    self.putcmd(cmd, args)
  File "/usr/lib64/python3.6/smtplib.py", line 367, in putcmd
    self.send(str)
  File "/usr/lib64/python3.6/smtplib.py", line 357, in send
    raise SMTPServerDisconnected('Server not connected')
smtplib.SMTPServerDisconnected: Server not connected
```

Not sure if that is helpful or not.

**Comment by HandyGuySoftware** [comment] 2020-02-10 02:23
OK, last try for the evening. I tried putting in an additional connect() call before the TLS call based on the error message ('smtplib.SMTPServerDisconnected: Server not connected'). In theory this should be unnecessary, but since nothing else makes sense I figured I'd give it a try.

New Issue_129 code was uploaded. Download it and give it a try.

HG

**Comment by g1bs0nsg** [comment] 2020-02-10 03:32
It does seem to be more reliable now, I ran it 5 times in a row and first 4 were successful and then it failed on the 5th with the smtplib.SMTPServerDisconnected: Server not connected error.

**Comment by HandyGuySoftware** [comment] 2020-02-10 03:46
Interesting. Well, that's a good sign. What was the information in the log file for the run that failed?

**Comment by g1bs0nsg** [comment] 2020-02-10 03:50
I still had to change the except line in order to get it to not throw the Exception_tls not defined line like I mentioned earlier.  But here is what I get in the log on a failed run:

```
EmailServer.Connect()
server=None keepalive=True
Initial connect using  SMTP
Initializing SMPT Object. Address=[smtp.1and1.com]  port=[587]
self.server=[<smtplib.SMTP object at 0x7f3340b0df60>]
connResult=[(220, b'perfora.net (mreueus001) Nemesis ESMTP Service ready')]
Starting TLS
Logging into server. Account=[REDACTED] pwd=[REDACTED]

```
and then the log ends.

**Comment by HandyGuySoftware** [comment] 2020-02-10 14:09
Still not making sense. The log says the connection but it still errors out. Added some more debug code to Issue_129 branch. Trying to narrow down the root cause, so please run it and send along the resulting logs.

Apologies for repeatedly running you through this debugging but I don't have a CentOS installation or a 1and1.com account to test with, and it seems like it's something with that specific configuration that is an issue.

**Comment by g1bs0nsg** [comment] 2020-02-11 01:02
Ok, got a new traceback with this one:

```
Traceback (most recent call last):
  File "/opt/test/dupReport/dupReport.py", line 297, in <module>
    globs.outServer.sendEmail(msgHtml, msgText)
  File "/opt/test/dupReport/dremail.py", line 635, in sendEmail
    self.server.sendmail(sender, receiver.split(','), msg.as_string().encode('utf-8'))
  File "/usr/lib64/python3.6/smtplib.py", line 861, in sendmail
    (code, resp) = self.mail(from_addr, esmtp_opts)
  File "/usr/lib64/python3.6/smtplib.py", line 534, in mail
    self.putcmd("mail", "FROM:%s%s" % (quoteaddr(sender), optionlist))
  File "/usr/lib64/python3.6/smtplib.py", line 367, in putcmd
    self.send(str)
  File "/usr/lib64/python3.6/smtplib.py", line 359, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
```

And this was in the log:

```
EmailServer.Connect()
server=None keepalive=True
Initial connect using  SMTP
Initializing SMPT Object. Address=[smtp.1and1.com]  port=[587]
self.server=[<smtplib.SMTP object at 0x7f5330de9518>]
connResult=[(220, b'perfora.net (mreueus001) Nemesis ESMTP Service ready')]
Starting TLS
TLS Exception: [[SSL: SSLV3_ALERT_ILLEGAL_PARAMETER] sslv3 alert illegal parameter (_ssl.c:877)]
Logging into server. Account=[REDACTED] pwd=[REDACTED]
SMTP Login Exception: [Server not connected]
Sending email to [*]
```

**Comment by HandyGuySoftware** [comment] 2020-02-11 03:10
OK, made a small change to the connnect() parameter values. It shouldn't make a difference, but none of this should be happening, so why not give it a try ;-) If this doesn't work I'm going to need to dig a little deeper to find the cause.

Pushed new Issue_129 code. Have a go and see what happens.

**Comment by g1bs0nsg** [comment] 2020-02-11 03:27
Getting the same traceback and log as the previous run.  I appreciate you checking into it for me.  You mentioned you didn't have a CentOS install to test on, what platform do you normally use?  I'm running this in a container on a proxmox hypervisor, I can spin up Ubuntu, Debian, Suse, etc and see if I get the same behavior. Also have Windows 10 and Fedora 29 available on my desktop/laptop machines.

**Comment by HandyGuySoftware** [comment] 2020-02-11 03:38
I develop on Windows 10 workstation and run my test & production on Debian 9.11.

**Comment by HandyGuySoftware** [comment] 2020-02-12 02:37
Still shooting in the dark on this. New Issue_129 code available. I'm trying a different SMTP initialization call with this. There's a couple of different things I'd like to try, but rather than upload 2 versions of the code, I'd like you to run it two ways.

1st run: download and execute the code just is comes from the Issue_129 branch. See what happens.

2nd run: Open dremail.py and comment out lines 167-174, so they look like this:

```
#                    connResult = self.server.connect(self.address,self.port)
#                    globs.log.write(3,'connResult=[{}]'.format(connResult))
#                    if self.encryption is not None:   # Do we need to use SSL/TLS?
#                        globs.log.write(3,'Starting TLS')
#                        try:
#                            self.server.starttls()
#                        except Exception as e:
#                            globs.log.write(3,'TLS Exception: [{}]'.format(e))
```

Save the file and run the program again. Let's see if either of those works.

I've also been doing some more digging and haven't found much discussion about this specific issue that seems relevant. I found a couple of links:

https://serverfault.com/questions/700655/sendmail-rejecting-some-connections-with-handshake-failure-ssl-alert-number-40

and

https://bugs.centos.org/view.php?id=9050

They both talk about similar issues, but I'm not sure either deals with your specific situation. However, passing them along in case reading either of them sparks any ideas on your end.

**Comment by g1bs0nsg** [comment] 2020-02-12 16:45
Ok, running it as written I get this traceback:

```
Traceback (most recent call last):
  File "/opt/test/dupReport/dupReport.py", line 297, in <module>
    globs.outServer.sendEmail(msgHtml, msgText)
  File "/opt/test/dupReport/dremail.py", line 588, in sendEmail
    self.connect()
  File "/opt/test/dupReport/dremail.py", line 165, in connect
    self.server = smtplib.SMTP_SSL(self.address,self.port)
  File "/usr/lib64/python3.6/smtplib.py", line 1031, in __init__
    source_address)
  File "/usr/lib64/python3.6/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib64/python3.6/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib64/python3.6/smtplib.py", line 1039, in _get_socket
    server_hostname=self._host)
  File "/usr/lib64/python3.6/ssl.py", line 365, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 773, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1033, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 645, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:877)
```

And in the log, it stops here:

```
EmailServer.Connect()
server=None keepalive=True
Initial connect using  SMTP
Initializing SMPT Object. Address=[smtp.1and1.com]  port=[587]
```

After commenting out the lines, I get the exact same traceback and log results.

I've got some time today, going to do some runs on Win10 and Debian and see if I'm getting the same results.

**Comment by HandyGuySoftware** [comment] 2020-02-12 17:08
OK, good. If all else fails, go back to the base 2.2.10 release and see what happens on those platforms.

**Comment by g1bs0nsg** [comment] 2020-02-12 17:46
So I can confirm I'm seeing the same errors on:

Win 10 with Python 3.8.1
Debian 9.12 with Python 3.5.3

So it must be something with 1and1... the odd thing is that I have been working on a python project myself that sends emails through the same host with the same email address, and I have no issues with that one.  But it is much more simple/rudimentary than what you have going on with dupReport.

This is my mail sending function:

```
import smtplib
import ssl
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

def sendList(store, currentList, conf):
    """
    Emails a copy of the requested shopping list
    to each email address that has been provided.
    """

    port = conf['server']['port']
    msg = MIMEMultipart()
    msg.set_unixfrom('author')
    msg['From'] = sender = conf['addresses']['sender']
    if isinstance(conf['addresses']['receiver'], list):
        msg['To'] = receiver = (",".join(conf['addresses']['receiver']))
    else:
        msg['To'] = receiver = conf['addresses']['receiver']
    msg['Subject'] = 'Shopping List for ' + store
    message = 'The current shopping list for ' + store + ' contains:\n\n'
    currentList.sort()
    for item in currentList:
        message += '%s\n' % item
    msg.attach(MIMEText(message))
    password = handlePassword()
    context = ssl.create_default_context()
    mailserver = conf['server']['host']
    server = smtplib.SMTP(mailserver, port)
    server.starttls(context=context)
    server.login(sender, password)
    server.sendmail(sender, receiver, msg.as_string())
    server.quit()
```

**Comment by HandyGuySoftware** [comment] 2020-02-12 17:53
Hmmm. The only real difference between your code and mine is the addition of the context object:

```
context = ssl.create_default_context()
.
.
server.starttls(context=context)

```

Can you try adding/modifying those lines in the dupReport code and see what happens?

**Comment by g1bs0nsg** [comment] 2020-02-12 18:22
Ah ha, so I had to add import ssl to dremail.py to make it work (otherwise was getting NameError: name 'ssl' is not defined), so after that when I ran it I still got a traceback:

```
Traceback (most recent call last):
  File "/opt/test/dupReport/dupReport.py", line 297, in <module>
    globs.outServer.sendEmail(msgHtml, msgText)
  File "/opt/test/dupReport/dremail.py", line 637, in sendEmail
    self.server.sendmail(sender, receiver.split(','), msg.as_string().encode('utf-8'))
  File "/usr/lib64/python3.6/smtplib.py", line 861, in sendmail
    (code, resp) = self.mail(from_addr, esmtp_opts)
  File "/usr/lib64/python3.6/smtplib.py", line 534, in mail
    self.putcmd("mail", "FROM:%s%s" % (quoteaddr(sender), optionlist))
  File "/usr/lib64/python3.6/smtplib.py", line 367, in putcmd
    self.send(str)
  File "/usr/lib64/python3.6/smtplib.py", line 359, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
```

But, it logged the real issue this time:

```
EmailServer.Connect()
server=None keepalive=True
Initial connect using  SMTP
Initializing SMPT Object. Address=[smtp.1and1.com]  port=[587]
self.server=[<smtplib.SMTP object at 0x7febb011b0f0>]
connResult=[(220, b'perfora.net (mreueus004) Nemesis ESMTP Service ready')]
Starting TLS
TLS Exception: [hostname 'smtp.1and1.com:587' doesn't match either of 'smtp.ionos.com', 'imap.ionos.com', 'pop.ionos.com', 'smtp.1and1.com', 'imap.1and1.com', 'pop.1and1.com', 'mx00.1and1.com', 'mx01.1and1.com', 'smtp.perfora.net', 'imap.perfora.net', 'pop.perfora.net', 'mout.perfora.net', 'mx00.perfora.net', 'mx01.perfora.net']
Logging into server. Account=[REDACTED] pwd=[REDACTED]
SMTP Login Exception: [Server not connected]
Sending email to [*]
```

So when I do the same to the release version it returns a little differently, says it's an ssl.CertificateError because the hostname doesn't match. 

```
Traceback (most recent call last):
  File "/opt/dupReport/dupReport.py", line 297, in <module>
    globs.outServer.sendEmail(msgHtml, msgText)
  File "/opt/dupReport/dremail.py", line 577, in sendEmail
    self.connect()
  File "/opt/dupReport/dremail.py", line 167, in connect
    self.server.starttls(context=context)
  File "/usr/lib64/python3.6/smtplib.py", line 771, in starttls
    server_hostname=self._host)
  File "/usr/lib64/python3.6/ssl.py", line 365, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 773, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1033, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 650, in do_handshake
    match_hostname(self.getpeercert(), self.server_hostname)
  File "/usr/lib64/python3.6/ssl.py", line 287, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
ssl.CertificateError: hostname 'smtp.1and1.com:587' doesn't match either of 'smtp.ionos.com', 'imap.ionos.com', 'pop.ionos.com', 'smtp.1and1.com', 'imap.1and1.com', 'pop.1and1.com', 'mx00.1and1.com', 'mx01.1and1.com', 'smtp.perfora.net', 'imap.perfora.net', 'pop.perfora.net', 'mout.perfora.net', 'mx00.perfora.net', 'mx01.perfora.net'
```

So my best guess is that these servers are load balanced, and maybe one of them has a different config from the rest and it accepts smtp.1and1.com:587 when the others won't... that's the only way I could think to explain why it sometimes works.

**Comment by HandyGuySoftware** [comment] 2020-02-12 19:31
Good note about importing the SSL library. never had an issue with that before but I guess it couldn't hurt to add it.

Not sure where to go from here. Do you have another email account you an use for backup notifications?

**Comment by g1bs0nsg** [comment] 2020-02-13 14:49
Yeah, I can always use gmail or some other service I'm sure.  1and1 is just the host for my personal domain.

**Comment by HandyGuySoftware** [comment] 2020-02-13 15:27
It might be worth opening a support ticket with 1and1 to see if they can fix the config error on their side, or at least give you a work-around.

**Comment by g1bs0nsg** [comment] 2020-02-13 15:28
Just as a test, I cloned the release version and made couple of changes to dremail.py and was able to run 10 times in a row with no failures.

I just added import ssl at the top, then made these changes in the try block at line 163:

```
try:
     self.server = smtplib.SMTP(self.address,self.port)
     if self.encryption is not None:   # Do we need to use SSL/TLS?
          context = ssl.create_default_context()
          self.server.starttls(context=context)
```
Removing the format from the server connect keeps it from passing to the server as smtp.1and1.com:587 and lets it properly match the hostname in the certificate and seems to resolve all the issues.

I wasn't entirely sure what the ssl.create_default_context() is doing, I just found that in a mail sending tutorial when I was working on my other app.  Looks like it is used to return a new context with secure default settings when wrapping sockets as SSLSocket objects according to the documentation:
https://docs.python.org/3/library/ssl.html

**Comment by HandyGuySoftware** [comment] 2020-02-13 15:38
Interesting. The separate system/port specification was in the last code set I uploaded, only using SMTP_SSL() instead of SMTP().

This is great! I will make that change to the code tonight and upload a new build. Run that for a bit and let's make sure it still works.

**Comment by HandyGuySoftware** [comment] 2020-02-13 15:40
Will also add the context creation as in your example.

**Comment by HandyGuySoftware** [comment] 2020-02-14 00:38
OK, new code has been uploaded to the Issue_129 branch. Try it out for a few days and if it looks stable I'll promote it to the master branch.

**Comment by g1bs0nsg** [comment] 2020-02-14 16:19
Ok, will report back in a few days and let you know.  Thanks.

**Comment by g1bs0nsg** [comment] 2020-02-17 18:09
Everything seems stable to me, I've gotten alerts at the scheduled time every morning like I used to.  I think this has resolved the issue.

**Comment by HandyGuySoftware** [comment] 2020-02-17 20:06
Perfect. I'll roll this up to production in the next couple of days.

**Comment by HandyGuySoftware** [comment] 2020-02-23 13:34
Fixed in Release_2.2.11

**Closed as completed by HandyGuySoftware** 2020-02-23 13:34 UTC
Labels: bug, 2.2.10
